# Generated by Django 5.2 on 2025-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="short_description",
            field=models.TextField(),
        ),
    ]
